version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - CACHE_BACKEND=redis
      - CACHE_TTL_SECONDS=300
      - LIMITER_MAX_REQ=10
      - LIMITER_TTL=60
      - LOG_LEVEL=info
      - HTTP_CLIENT_TIMEOUT_SECONDS=10
      - REDIS_ADDR=redis:6379
      - REDIS_PASSWORD=
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 3s
      retries: 3

volumes:
  redis-data:

networks:
  app-network:
    driver: bridge